const TIERS=[{min:100000,rate:.15},{min:50000,rate:.125},{min:25000,rate:.10},{min:10000,rate:.075},{min:0,rate:.05}];
const rate=n=>TIERS.find(x=>n>=x.min)?.rate??.05;
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const cors={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type'};
async function getProducts(env){const r=await env.ASSETS.fetch(new Request('https://assets.local/assets/products.json'));if(!r.ok)throw Error('Product catalogue unavailable');return r.json()}
async function api(req,env){const u=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});try{
 if(u.pathname==='/api/health')return json({ok:true,service:'ELECVERO B2B API',database:Boolean(env.DB),time:new Date().toISOString()});
 if(u.pathname==='/api/products'&&req.method==='GET'){const all=await getProducts(env),q=(u.searchParams.get('q')||'').trim().toLowerCase(),cat=u.searchParams.get('category')||'',list=all.filter(p=>{const h=`${p.display_name||''} ${p.description||''} ${p.sku||''} ${p.display_category||''}`.toLowerCase();return(!q||h.includes(q))&&(!cat||p.display_category===cat)});return json({count:list.length,products:list})}
 if(u.pathname==='/api/quote'&&req.method==='POST'){const all=await getProducts(env),map=new Map(all.map(p=>[p.sku,p])),b=await req.json(),items=Array.isArray(b.items)?b.items:[],lines=items.map(i=>{const p=map.get(i.sku),qty=Math.max(1,Math.floor(Number(i.qty||1)));return p?{sku:p.sku,name:p.display_name,qty,unit_price:Number(p.mrp||0),line_total:Number(p.mrp||0)*qty}:null}).filter(Boolean),sub=lines.reduce((s,x)=>s+x.line_total,0),r=rate(sub),disc=sub*r;return json({subtotal:sub,discount_rate:r,discount_amount:disc,total:sub-disc,items:lines})}
 if(u.pathname==='/api/orders'&&req.method==='POST'){if(!env.DB)return json({ok:false,error:'D1 database is not configured yet.'},503);const all=await getProducts(env),map=new Map(all.map(p=>[p.sku,p])),b=await req.json(),items=Array.isArray(b.items)?b.items:[],lines=items.map(i=>{const p=map.get(i.sku),qty=Math.max(1,Math.floor(Number(i.qty||1)));return p?{sku:p.sku,name:p.display_name,qty,unit_price:Number(p.mrp||0),line_total:Number(p.mrp||0)*qty}:null}).filter(Boolean);if(!lines.length)return json({ok:false,error:'No valid products in order.'},400);const sub=lines.reduce((s,x)=>s+x.line_total,0),r=rate(sub),disc=sub*r,total=sub-disc,ref=`EV-${Date.now().toString(36).toUpperCase()}`,c=b.customer||{};const cr=await env.DB.prepare('INSERT INTO customers (business_name,contact_name,phone,email,city,gstin) VALUES (?,?,?,?,?,?)').bind(c.business_name||'Website Customer',c.contact_name||'',c.phone||'',c.email||'',c.city||'',c.gstin||'').run();const cid=cr.meta.last_row_id;const or=await env.DB.prepare('INSERT INTO orders (order_ref,customer_id,subtotal,discount_rate,discount_amount,total) VALUES (?,?,?,?,?,?)').bind(ref,cid,sub,r,disc,total).run();const oid=or.meta.last_row_id;for(const x of lines)await env.DB.prepare('INSERT INTO order_items (order_id,sku,product_name,qty,unit_price,line_total) VALUES (?,?,?,?,?,?)').bind(oid,x.sku,x.name,x.qty,x.unit_price,x.line_total).run();return json({ok:true,order_ref:ref,subtotal:sub,discount_rate:r,discount_amount:disc,total})}
 return json({ok:false,error:'API route not found.'},404)
}catch(e){return json({ok:false,error:e?.message||'Server error'},500)}}
export default {async fetch(req,env){const u=new URL(req.url);if(u.pathname.startsWith('/api/')){const r=await api(req,env),h=new Headers(r.headers);for(const[k,v]of Object.entries(cors))h.set(k,v);return new Response(r.body,{status:r.status,headers:h})}return env.ASSETS.fetch(req)}};
